#!/bin/sh

# KEYWORD: firstboot
# PROVIDE: firstboot_pot
# REQUIRE: NETWORKING
# BEFORE: LOGIN

# firstboot_pot_enable="YES"
# firstboot_pot_ns="ns1 ns2..."
# firstboot_pot_update="YES"
# firstboot_pot_root_pk="ssh-ed25519..."
# firstboot_pot_user="user"
# firstboot_pot_user_pk="ssh-ed25519..."
# firstboot_pot_pkgs="pkg pkg..."
# firstboot_pot_cmd="cmd"

. /etc/rc.subr

: ${firstboot_pot_enable:="NO"}

name="firstboot_pot"
rcvar=firstboot_pot_enable
start_cmd="firstboot_pot_run"
stop_cmd=":"

firstboot_pot_run()
{
    # Set NS first
    if [ ! -z "${firstboot_pot_ns}" ]; then
        echo "Setting Nameservers:"
        printf 'nameserver %s\n' ${firstboot_pot_ns} | tee /etc/resolv.conf
    fi
    
    # Test network
    _c=0
    while [ $((_c=_c+1)) -lt 5 ] && ! ping6 -X2 -c1 freebsd.org; do
        sleep 1
    done

    # Update
    if [ ${firstboot_pot_update} = YES ]; then
        freebsd-update fetch --not-running-from-cron | cat
        freebsd-update install --not-running-from-cron || echo No updates available
    fi

    # Packages
    if [ ! -z "${firstboot_pot_pkgs}" ]; then
        # Bootstrap and update pkg
        env ASSUME_ALWAYS_YES=YES pkg bootstrap -f | cat
        env ASSUME_ALWAYS_YES=YES pkg update -f | cat
        # Install packages
        for package in ${firstboot_pot_pkgs}; do
            env ASSUME_ALWAYS_YES=YES pkg install ${package} </dev/null | cat
        done
    fi

    # Root ssh key
    if [ ! -z "${firstboot_pot_root_pk}" ]; then
        umask 077
        mkdir /root/.ssh
        echo ${firstboot_pot_root_pk} | tee /root/.ssh/authorized_keys
    fi

    # User setup
    if [ ! -z "${firstboot_pot_user}" ]; then
        umask 077
        pw useradd -n ${firstboot_pot_user} -m -s /bin/sh -h -
        mkdir /home/${firstboot_pot_user}/.ssh
        if [ ! -z "${firstboot_pot_user_pk}" ]; then
            echo ${firstboot_pot_user_pk} | tee /home/${firstboot_pot_user}/.ssh/authorized_keys
        fi
    fi

    # Run firstboot command
    if [ ! -z "${firstboot_pot_cmd}" ]; then
        /bin/sh -c "${firstboot_pot_cmd}" 
    fi
}

load_rc_config $name
run_rc_command "$1"
